Repository wecode-bootcamp-korea/19-1st-whiteSpace-frontend, pull requests merged in 2021-04, with the labels that each got.

#1 [19기 김동현] Fix : 리뷰사항 반영 후 commit 완료
  .eslintrc
  public/data/category.json
  src/Components/Nav/Component/NavMenuList.js
  src/Components/Nav/Component/NavMenuList.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Routes.js
  src/Styles/common.scss
Labels: Status: 리뷰 요청

#4 [19기 박단비] Add : 회원가입페이지 레이아웃 & 기능
  public/index.html
  src/Pages/Login/Login.scss
  src/Pages/Signup/Signup.js
  src/Pages/Signup/Signup.scss
  src/Pages/Signup/Welcome/Welcome.js
  src/Pages/Signup/Welcome/Welcome.scss
  src/config.js
Labels: Status: 리뷰 요청

#3 [19기 김남선] Modify : master pull 받은 후 conflict해결
  .eslintrc
  .eslintrc.json
  .prettierrc.json
  package-lock.json
  public/data/categoryProductData.json
  public/data/mainImageData.json
  public/data/productData.json
  src/Components/Paging/Paging.js
  src/Components/Paging/Paging.scss
  src/Components/Paging/PagingTest.js
  src/Components/ProductWrap/ProductWrap.js
  src/Components/ProductWrap/ProductWrap.scss
  src/Pages/CategoryProduct/CategoryProduct.js
  src/Pages/CategoryProduct/CategoryProduct.scss
  src/Pages/Main/Components/BestProduct/BestProduct.js
  src/Pages/Main/Components/Slider/Slider.js
  src/Pages/Main/Components/Slider/Slider.scss
  src/Pages/Main/Components/SliderContents/SliderContents.js
  src/Pages/Main/Components/SliderContents/SliderContents.scss
  src/Pages/Main/Main.js
  src/Pages/ProductList/Components/Product/Product.js
  src/Pages/ProductList/Components/Product/Product.scss
  src/Pages/ProductList/Components/StatusBtn/StatusBtn.js
  src/Pages/ProductList/Components/StatusBtn/StatusBtn.scss
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductList.scss
  src/Routes.js
  src/Styles/common.scss
  src/config.js
Labels: Status: 리뷰 요청

#5 [19기 김남선] Modify : 리뷰 수정사항 반영 및 conflict해결
  src/Pages/ProductDetail/Components/AddReview/AddReview.js
  src/Pages/ProductDetail/Components/AddReview/AddReview.scss
  src/Pages/ProductDetail/Components/AddReview/reviewData.js
  src/Pages/ProductDetail/Components/Modal/Modal.js
  src/Pages/ProductDetail/Components/Modal/Modal.scss
  src/Pages/ProductDetail/Components/Review/Review.js
  src/Pages/ProductDetail/Components/ReviewStar/ReviewStar.js
  src/Pages/ProductDetail/Components/ReviewStar/ReviewStar.scss
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/ProductDetail.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#7 [19기 박단비] Singup & Nav bar Merge
  src/Pages/Login/Login.js
  src/Pages/Signup/Signup.js
  src/Pages/Signup/Signup.scss
  src/Routes.js
Labels: Status: Accepted

#6 [19기 박단비] Login & Nav bar Merge, api수정
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Signup/Signup.js
  src/Routes.js
  src/Styles/common.scss
  src/config.js
Labels: Status: Accepted, Status: 리뷰 요청

#12 [19기 김남선] Add : 결제완료 페이지 레이아웃 완료 및 컴포넌트 분리
  public/data/orderData.json
  src/Components/InfomationWrap/InfomationWrap.js
  src/Components/InfomationWrap/InfomationWrap.scss
  src/Pages/Order/Components/OrderComplete/OrderComplete.js
  src/Pages/Order/Components/OrderComplete/OrderComplete.scss
  src/Pages/Order/Components/OrderInfo/OrderInfo.js
  src/Pages/Order/Components/OrderInfo/OrderInfo.scss
  src/Pages/Order/Components/PayInfo/PayInfo.js
  src/Pages/Order/Components/PayInfo/PayInfo.scss
  src/Pages/Order/Components/ShippingLocation/ShippingLocation.js
  src/Pages/Order/Components/ShippingLocation/ShippingLocation.scss
  src/Pages/Order/Components/TableWrap/TableWrap.js
  src/Pages/Order/Components/TableWrap/TableWrap.scss
  src/Pages/Order/Components/TotalPrice/TotalPrice.js
  src/Pages/Order/Components/TotalPrice/TotalPrice.scss
  src/Pages/Order/Order.js
  src/Pages/Order/Order.scss
  src/Pages/Signup/Signup.js
  src/Routes.js
Labels: Status: 리뷰 진행중

#8 [19기 김동현] FIX : nav className 공백 수정 및 url 일부 수정
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Routes.js
Labels: Status: 수정 요청

#13 [19기 김동현] Fix : Conflict 에러 해결
  src/Components/Footer/Component/CorpLi.js
  src/Components/Footer/Component/CorpLi.scss
  src/Components/Footer/Component/Tos.js
  src/Components/Footer/Component/Tos.scss
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Pages/Main/Main.scss
Labels: Status: 리뷰 요청

#9 [19기 김동현] Modify : popup 버튼 사용, 버튼 css 수정
  src/Components/Nav/Component/Carousel.js
  src/Components/Nav/Component/Carousel.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/Popup.js
  src/Routes.js
Labels: Status: Accepted

#11 [19기 김남선] conflict해결 및 수정사항 반영
  public/data/categoryProductData.json
  public/data/productData.json
  src/Components/Nav/Component/NavMenuList.js
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Paging/Paging.js
  src/Components/Paging/Paging.scss
  src/Components/Paging/PagingTest.js
  src/Components/TopButton/TopButton.js
  src/Components/TopButton/TopButton.scss
  src/Pages/CategoryProduct/CategoryProduct.js
  src/Pages/Main/Components/Slider/Slider.js
  src/Pages/ProductList/Components/Product/Product.js
  src/Routes.js
  src/index.js
Labels: Status: 리뷰 요청

#19 [19기 김남선] Modify : footer, top button scss수정
  public/data/productData.json
  src/Components/Footer/Component/Tos.scss
  src/Components/Footer/Footer.scss
  src/Components/Nav/Nav.scss
  src/Components/TopButton/TopButton.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#14 [19기 김남선] CategoryProductList : conflict 해결
  src/Pages/CategoryProduct/CategoryProduct.js
  src/Pages/ProductList/Components/Product/Product.js
  src/Routes.js
Labels: Status: 리뷰 요청

#16 [19기 김동현] Fix : Conflict 해결
  src/Components/Footer/Component/Tos.scss
  src/Components/Footer/Footer.scss
Labels: Status: 리뷰 요청

#17 [19기 김동현] Fix : Conflict 해결
  src/Components/Nav/Component/NavMenuList.js
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#15 [19기 김동현] Modify : corsur 부분 ref 사용에서 css 처리로 변경
  src/Components/Nav/Component/Carousel.js
  src/Components/Nav/Component/Carousel.scss
  src/Components/Nav/Popup.js
Labels: Status: 리뷰 요청

#18 [19기 김남선] Search : conflict해결 및 master pull
  public/data/category.json
  src/Components/Nav/Component/NavMenuList.js
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Paging/Paging.scss
  src/Components/ProductWrap/ProductWrap.js
  src/Components/ProductWrap/ProductWrap.scss
  src/Pages/CategoryProduct/CategoryProduct.js
  src/Pages/Order/Components/OrderComplete/OrderComplete.js
  src/Pages/ProductList/Components/Product/Product.js
  src/Pages/ProductList/Components/Product/Product.scss
  src/Pages/ProductList/ProductList.scss
  src/Pages/SearchPage/SearchPage.js
Labels: Status: 리뷰 요청

#21 [19기 박단비] ProductDetail 상세페이지 레이아웃, 기능 완성
  public/data/data.js
  src/Pages/ProductDetail/Components/ProductBtn.js
  src/Pages/ProductDetail/Components/ProductBtn.scss
  src/Pages/ProductDetail/Components/ProductDesc.js
  src/Pages/ProductDetail/Components/ProductDesc.scss
  src/Pages/ProductDetail/Components/ProductDescImg.js
  src/Pages/ProductDetail/Components/ProductDescImg.scss
  src/Pages/ProductDetail/Components/ProductOpt.js
  src/Pages/ProductDetail/Components/ProductOpt.scss
  src/Pages/ProductDetail/Components/ProductSubImg.js
  src/Pages/ProductDetail/Components/ProductSubImg.scss
  src/Pages/ProductDetail/Components/ProductTotalPrice.js
  src/Pages/ProductDetail/Components/ProductTotalPrice.scss
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/ProductDetail.scss
  src/Pages/ProductList/Components/Product/Product.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#20 [19기 김남선] Modify : conflict 해결 및 코드 리뷰 반영
  src/Pages/Order/Components/OrderComplete/OrderComplete.js
  src/Pages/Order/Components/OrderInfo/OrderInfo.js
  src/Pages/Order/Components/OrderInfo/OrderInfo.scss
  src/Pages/Order/Components/PayMethod/PayMethod.js
  src/Pages/Order/Components/PayMethod/PayMethod.scss
  src/Pages/Order/Components/ShippingLocation/ShippingLocation.js
  src/Pages/Order/Components/ShippingLocation/ShippingLocation.scss
  src/Pages/Order/Order.js
  src/Pages/Order/Order.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#22 [19기 김동현] Fix : 수정사항 반영, conflict 해결
  public/data/cartData.json
  src/Pages/Cart/Cart.js
  src/Pages/Cart/Cart.scss
  src/Pages/Cart/Cart.zip
  src/Pages/Cart/Component/CartButton.js
  src/Pages/Cart/Component/CartButton.scss
  src/Pages/Cart/Component/CartTotalPrice.js
  src/Pages/Cart/Component/CartTotalPrice.scss
  src/Pages/Cart/Component/Checkbox.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#23 [19기 김남선] Modify : conflict 해결
  src/Components/Nav/Nav.js
  src/Pages/CategoryProduct/CategoryProduct.js
  src/Pages/Main/Components/Slider/Slider.js
  src/Pages/Main/Components/Slider/Slider.scss
  src/Pages/Main/Components/SliderContents/SliderContents.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/ProductDetail/Components/ProductReview/ProductReview.js
  src/Pages/SearchPage/SearchPage.js
  src/config.js
Labels: Status: Conflict 발생

#25 [19기 김남선] Modify : conflict 해결 및 api 통신주소 config.js로 관리
  src/Components/Nav/Nav.js
  src/Pages/Cart/Cart.js
  src/Pages/CategoryProduct/CategoryProduct.js
  src/Pages/Login/Login.js
  src/Pages/Main/Main.js
  src/Pages/ProductDetail/Components/AddReview/AddReview.js
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductList/Components/Product/Product.js
  src/Pages/ProductList/Components/Product/Product.scss
  src/Pages/SearchPage/SearchPage.js
  src/Pages/Signup/Signup.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#24 [19기 김남선] Modify : conflict수정
  src/Pages/ProductDetail/Components/AddReview/AddReview.js
  src/Pages/ProductDetail/Components/ProductReview/ProductReview.js
  src/Pages/ProductDetail/Components/ProductReview/ProductReview.scss
  src/Pages/ProductDetail/Components/Review/Review.js
  src/Pages/ProductDetail/Components/Review/Review.scss
  src/Pages/ProductDetail/Components/ReviewList/ReviewList.js
  src/Pages/ProductDetail/Components/ReviewStar/ReviewStar.js
  src/Pages/ProductDetail/Components/ReviewStar/ReviewStar.scss
Labels: Status: 리뷰 요청

#27 [19기 김남선] Modify : merge 후 수정사항
  src/Pages/Cart/Cart.js
  src/Pages/Login/Login.js
  src/Pages/Main/Main.js
  src/Pages/ProductDetail/Components/AddReview/AddReview.js
  src/Pages/ProductDetail/Components/ProductBtn.js
  src/Pages/ProductDetail/Components/ProductDescImg.js
  src/Pages/ProductDetail/Components/ProductOpt.js
  src/Pages/ProductDetail/Components/ProductReview/ProductReview.js
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/Signup/Welcome/Welcome.js
  src/Routes.js
Labels: Status: 리뷰 요청

#28 [19기 김동현] Fix : merge to master
  src/Pages/Cart/Cart.js
  src/Pages/Cart/Cart.scss
  src/Pages/Cart/Cart.zip
  src/Pages/Cart/Component/CartButton.js
  src/Pages/Cart/Component/CartButton.scss
Labels: Status: 리뷰 요청

#30 [19기 김남선] Modify : conflict해결
  src/Components/Footer/Footer.scss
  src/Components/Nav/Nav.js
  src/Pages/Cart/Cart.js
  src/Pages/CategoryProduct/CategoryProduct.js
  src/Pages/Login/Login.js
  src/Pages/Main/Main.js
  src/Pages/ProductDetail/Components/AddReview/AddReview.js
  src/Pages/ProductDetail/Components/AddReview/AddReview.scss
  src/Pages/ProductDetail/Components/ProductReview/ProductReview.js
  src/Pages/ProductDetail/Components/ReviewStar/ReviewStar.js
  src/config.js
Labels: Status: 리뷰 요청

#29 [19기 김동현] Add : 로그아웃 기능 추가 작업 중
  src/Components/Nav/Component/NavMenuList.js
  src/Components/Nav/Nav.js
Labels: Status: Accepted

#33 [19기 김남선] Modify : final수정
  src/Pages/Cart/Cart.js
  src/Pages/Cart/Component/CartButton.scss
  src/Pages/Order/Components/ShippingLocation/AddressModal.scss
  src/Pages/ProductDetail/ProductDetail.js
Labels: Status: 리뷰 요청

#35 [19기 김동현] Add : cart 기능 수정
  src/Components/Nav/Nav.js
  src/Pages/Cart/Cart.js
  src/Pages/Cart/Cart.scss
  src/Pages/ProductDetail/Components/ProductReview/ProductReview.js
  src/Pages/ProductDetail/Components/ReviewStar/ReviewStar.js
  src/config.js
Labels: Status: 리뷰 요청

#36 [19기 김남선] conflict 해결 및 최종 수정
  src/Pages/Order/Components/OrderInfo/OrderInfo.js
  src/Pages/Order/Components/ShippingLocation/AddressModal.scss
Labels: Status: 리뷰 요청
